"""test init migration

Revision ID: 57041490801a
Revises:
Create Date: 2024-03-06 11:49:55.537650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "57041490801a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4269,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("gps_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index(
    #     "idx_vehicles_geom",
    #     "vehicles",
    #     ["geom"],
    #     unique=False,
    #     postgresql_using="gist",
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(
    #     "idx_vehicles_geom", table_name="vehicles", postgresql_using="gist"
    # )
    op.drop_table("vehicles")
    # ### end Alembic commands ###
