version: '3.9'
services:

  postgis:
    build:
      context: ../
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d db" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    expose:
      - "5432"
    networks:
      - services

  migrations:
    build:
      context: ../
      dockerfile: ./src/migrations/Dockerfile
    container_name: migrations
    environment:
      - POSTGRES_HOST=postgis
    env_file:
      - ../.env
    restart: no
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - services

  exel_to_postgis:
    build:
      context: ../
      dockerfile: ./src/exel_to_postgis/Dockerfile
    container_name: exel_to_postgis
    environment:
      - POSTGRES_HOST=postgis
    env_file:
      - ../.env
    restart: no
    depends_on:
      - migrations
    networks:
      - services

volumes:
  postgres_data:

networks:
  services:
    name: test_infra
